pub mod action;
pub mod ai;
pub mod calendar;
pub mod company;
pub mod game_speed;
pub mod globals;
pub mod new_game;
pub mod person;
pub mod project;
pub mod registries;
pub mod resources;
pub mod sim_date;
pub mod systems;
pub mod team;
pub mod utils;
mod locations;
mod talent_generation;
pub mod persistence;
