name: PR Cargo Test

on:
  pull_request:
    branches:
      - develop

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-requisite
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev webkit2gtk-4.1
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo test
        run: cargo test --manifest-path src-tauri/Cargo.toml --locked --verbose
