name: PR Cargo Test

on:
  pull_request:
    branches:
      - develop

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Run cargo test
        run: cargo test --manifest-path src-tauri/Cargo.toml --locked --verbose
