use std::collections::HashMap;
use std::sync::OnceLock;
use crate::sim::person::skills::{GlobalSkill, SkillId};

#[derive(Debug, Clone)]
pub struct SkillDef {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub domain: &'static str,
    pub related_stats: &'static [&'static str],
    pub tier: &'static str,
    pub feedforward: &'static [&'static str],
    pub feedback: &'static [&'static str],
}
pub static GLOBAL_SKILLS: OnceLock<HashMap<SkillId,GlobalSkill>> = OnceLock::new();
pub const SKILL_DEFS: &[SkillDef] = &[
    SkillDef {
        id: "abstraction-modeling",
        name: "Abstraction Modeling",
        description: "Ability to structure complex ideas into reusable or generalized patterns.",
        domain: "Execution, Contextual",
        related_stats: &["Creativity", "Systems"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "accountability-framing",
        name: "Accountability Framing",
        description: "Skill in defining and assigning clear ownership for responsibilities and outcomes.",
        domain: "Coordination",
        related_stats: &["Discipline", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "active-listening",
        name: "Active Listening Instinct",
        description: "Pays focused attention and seeks full understanding before responding.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "assumption-tracking",
        name: "Assumption Tracking",
        description: "Recognizes and monitors unstated assumptions that may impact work quality or direction.",
        domain: "Execution",
        related_stats: &["Precision", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "bottleneck-awareness",
        name: "Bottleneck Awareness",
        description: "Identifies points in a process or system where work is delayed or constrained.",
        domain: "Coordination",
        related_stats: &["Systems", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "capacity-modeling",
        name: "Capacity Modeling Intuition",
        description: "Knowing the limits of what a team can do.",
        domain: "Coordination",
        related_stats: &["Empathy", "Judgement", "Resilience"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "clarity-drive",
        name: "Clarity Drive",
        description: "Urge to reduce misunderstanding with examples or structure. Habit of simplifying or checking understanding.",
        domain: "Interpersonal",
        related_stats: &["Communication", "Discipline"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "computational-limits",
        name: "Computational Limits Awareness",
        description: "Understands basic resource constraints even in abstract.",
        domain: "Execution",
        related_stats: &["Systems", "Precision"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "context-awareness",
        name: "Contextual Awareness",
        description: "Sensing social hierarchy, stakes, or norms.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Adaptability"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "defensiveness-resistance",
        name: "Defensiveness Resistance",
        description: "Receiving critique without closing off.",
        domain: "Interpersonal",
        related_stats: &["Resilience", "Adaptability"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "edge-case-sensitivity",
        name: "Edge Case Sensitivity",
        description: "Naturally notices outliers or problematic conditions.",
        domain: "Execution",
        related_stats: &["Precision", "Creativity"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "goal-alignment",
        name: "Goal Alignment Sensitivity",
        description: "Detecting when work is misaligned with strategic intent.",
        domain: "Coordination",
        related_stats: &["Focus", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "intent-modeling",
        name: "Intent Modeling",
        description: "Guessing what someone is trying to say beyond words.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Creativity"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "logical-reasoning",
        name: "Logical Reasoning",
        description: "Ability to reason through cause/effect and structured logic.",
        domain: "Execution",
        related_stats: &["Judgement", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "modifiability-instinct",
        name: "Modifiability Instinct",
        description: "Awareness of whether a solution needs to be rigid, flexible, or templated.",
        domain: "Contextual, Execution",
        related_stats: &["Adaptability", "Systems"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "monetization-literacy",
        name: "Monetization Literacy",
        description: "Understanding of how software makes or saves money.",
        domain: "Contextual",
        related_stats: &["Judgement", "Creativity"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "motivation-mapping",
        name: "Motivation Mapping",
        description: "Grasping what drives different team members.",
        domain: "Coordination",
        related_stats: &["Empathy", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "multi-tenant-thinking",
        name: "Multi-Tenant Thinking",
        description: "Understands shared system implications.",
        domain: "Contextual",
        related_stats: &["Systems", "Precision"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "opportunity-cost",
        name: "Opportunity Cost Awareness",
        description: "Recognizing trade-offs in decisions.",
        domain: "Coordination",
        related_stats: &["Judgement", "Systems"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "org-scaffolding",
        name: "Organizational Scaffolding",
        description: "Mental image of how teams and communication should be structured.",
        domain: "Coordination",
        related_stats: &["Systems", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "personalization-awareness",
        name: "Personalization Awareness",
        description: "Recognizes when a domain expects tailored experiences.",
        domain: "Contextual",
        related_stats: &["Empathy", "Creativity"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "perspective-taking",
        name: "Perspective-Taking",
        description: "Grasping how others might perceive a situation.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Adaptability"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "positive-reinforcement",
        name: "Positive Reinforcement Instinct",
        description: "Tendency to highlight or uplift others' contributions.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "prioritization",
        name: "Prioritization",
        description: "Understanding what matters more, and why.",
        domain: "Coordination, Execution",
        related_stats: &["Discipline", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "problem-solving",
        name: "Problem Solving",
        description: "Ability to break down complex issues into solvable parts.",
        domain: "Execution",
        related_stats: &["Creativity", "Resilience", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "product-market-fit-instinct",
        name: "Product-Market Fit Instinct",
        description: "Sense of what it means for a product to 'click'.",
        domain: "Contextual",
        related_stats: &["Empathy", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "rapport-detection",
        name: "Rapport Detection",
        description: "Recognizing when connection is strong or broken.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "regulatory-literacy",
        name: "Regulatory Literacy",
        description: "Understands that software may be shaped by rules.",
        domain: "Contextual",
        related_stats: &["Precision", "Discipline"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "requirement-clarity-seeking",
        name: "Requirement Clarity Seeking",
        description: "Tendency to dig beneath vague requests.",
        domain: "Execution",
        related_stats: &["Communication", "Precision"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "risk-intuition",
        name: "Risk Intuition",
        description: "Judging downside exposure realistically.",
        domain: "Coordination, Contextual",
        related_stats: &["Resilience", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "scale-sensitivity",
        name: "Scale Sensitivity",
        description: "Understands that some domains operate at scale.",
        domain: "Contextual",
        related_stats: &["Systems", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "stakeholder-complexity",
        name: "Stakeholder Complexity Sensitivity",
        description: "Understands multi-user/power structures.",
        domain: "Contextual",
        related_stats: &["Empathy", "Adaptability"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "systems-thinking",
        name: "Systems Thinking",
        description: "Understanding how people, processes, and outcomes interact.",
        domain: "Coordination, Execution",
        related_stats: &["Systems", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "tech-debt-awareness",
        name: "Technical Debt Awareness",
        description: "Understands tradeoffs between short-term and long-term costs.",
        domain: "Execution",
        related_stats: &["Discipline", "Judgement"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "test-case-intuition",
        name: "Test Case Intuition",
        description: "Instinct to think about how something could fail.",
        domain: "Execution",
        related_stats: &["Precision", "Focus"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "tone-awareness",
        name: "Tone Awareness",
        description: "Internal gauge for emotional nuance in speech.",
        domain: "Interpersonal",
        related_stats: &["Empathy", "Adaptability"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "trust-building",
        name: "Trust-Building Tendency",
        description: "Natural inclination to signal openness or honesty.",
        domain: "Interpersonal",
        related_stats: &["Resilience", "Communication"],
        tier: "foundational",
        feedforward: &[],
        feedback: &[],
    },
];

pub const SME_RETAIL_SKILLS: &[SkillDef] = &[
    SkillDef {
        id: "ease-of-use-awareness",
        name: "Ease of Use Awareness",
        description: "Designs interfaces that require no manual or explanation, based on real-world observation of confused or hesitant users. Frequently trims unnecessary controls or restructures flows to support first-time use without guidance.",
        domain: "Contextual",
        related_stats: &["Empathy", "Discipline"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "low-tech-user-design",
        name: "Low-Tech User Design",
        description: "Builds with low-tech field users in mind — those who forget passwords, never check settings, and fear 'breaking something'. Incorporates forgiving workflows and avoids technical jargon or hidden state.",
        domain: "Contextual",
        related_stats: &["Empathy", "Communication"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "offline-tolerant-design",
        name: "Offline-Tolerant Design",
        description: "Understands how to design systems that gracefully degrade or sync when offline. Useful for mobile and rural contexts where connectivity is inconsistent.",
        domain: "Execution",
        related_stats: &["Systems", "Judgement"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "mobile-first-instinct",
        name: "Mobile-First Instinct",
        description: "Naturally considers mobile constraints — screen size, touch input, limited bandwidth — when thinking through UI or system behavior.",
        domain: "Execution",
        related_stats: &["Adaptability", "Systems"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "self-guided-ux",
        name: "Self-Guided UX",
        description: "Optimizes interfaces so that sales reps and clerks can operate them immediately, without training sessions or written guides. Favors flat hierarchies, visual cues, and obvious next steps based on repeated exposure to confused first-time users.",
        domain: "Contextual",
        related_stats: &["Empathy", "Precision"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "entry-speed-optimization",
        name: "Entry Speed Optimization",
        description: "Focuses on minimizing friction in repetitive input workflows. Familiar with bulk entry patterns, shortcuts, and latency sensitivity.",
        domain: "Execution",
        related_stats: &["Focus", "Discipline"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "audit-sensitivity",
        name: "Audit Sensitivity",
        description: "Understands the need for traceability of user actions, even if the client doesn’t use that term. Designs for accountability without assuming trust.",
        domain: "Contextual",
        related_stats: &["Judgement", "Precision"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "data-integrity-prioritization",
        name: "Data Integrity Prioritization",
        description: "Instinctively guards against data corruption, overwrites, and loss. Knows where failure modes lie in sync, concurrency, or manual override systems.",
        domain: "Execution",
        related_stats: &["Systems", "Resilience"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "role-based-workflow-design",
        name: "Role-Based Workflow Design",
        description: "Implements role-based workflows based on on-the-ground experience — e.g., sales reps shouldn’t be able to change invoices, managers shouldn’t need to key in every transaction. Anticipates tension between access and responsibility.",
        domain: "Contextual",
        related_stats: &["Judgement", "Empathy"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
    SkillDef {
        id: "low-overhead-maintainability",
        name: "Low-Overhead Maintainability",
        description: "Designs systems that require minimal babysitting. Avoids brittle configurations, unnecessary dependencies, and user-facing traps that increase long-term support cost.",
        domain: "Execution",
        related_stats: &["Discipline", "Systems"],
        tier: "Applied",
        feedforward: &[],
        feedback: &[],
    },
];
